In [1]:
import tensorflow as tf
tf.__version__
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3722729622034724602,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 1703411712
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 18234789716542847760
 physical_device_desc: "device: 0, name: GeForce MX150, pci bus id: 0000:01:00.0, compute capability: 6.1"]

In [1]:
import numpy as np
X  = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
A1 = np.dot(X, W1) + B1
print(A1.shape)

(3,)


In [13]:
import tensorflow as tf
import numpy as np
#r1 = tf.keras.activations.relu()
x = tf.Variable(np.array([1.,-1.,2.,-2.]))
with tf.GradientTape() as tape:
    y = tf.nn.relu(x)
print(y)
#x = np.array([1,-1,2,-2])
#y = tf.keras.activations.relu(x).forward(x)
#dx = r1.backward(np.array([-3,3,3,3]))
x2 = tf.Variable(np.array([-3.,3.,3.,3.]))
dx = tape.gradient(y, x)
print(dx)

tf.Tensor([1. 0. 2. 0.], shape=(4,), dtype=float64)
tf.Tensor([1. 0. 1. 0.], shape=(4,), dtype=float64)


In [16]:
class ReLU:
    def __init__(self):
        self.chk = None
 
    def forward(self, x):
        self.chk = (x>0).astype(np.int)
        print(self.chk)
        return x * self.chk
 
    def backward(self, dout):
        return dout * self.chk

r1 = ReLU()
x = np.array([1,-1,2,-2])
y = r1.forward(x)
print(y)
dx = r1.backward(np.array([-3,3,3,3]))
print(dx)

[1 0 1 0]
[1 0 2 0]
[-3  0  3  0]


In [22]:
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(28,28,3)))
model.add(tf.keras.layers.Conv2D(6, (5,5), strides=1, padding='valid'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 24, 24, 6)         456       
Total params: 456
Trainable params: 456
Non-trainable params: 0
_________________________________________________________________
